
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var r={},x;for(x in f)f.hasOwnProperty(x)&&(r[x]=f[x]);var aa="./this.program",y=!1,z=!1,ba=!1,ca=!1;y="object"===typeof window;z="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!y&&!ba&&!z;var A="",B,C,da,ea;
if(ba)A=z?require("path").dirname(A)+"/":__dirname+"/",B=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);return da.readFileSync(a,b?null:"utf8")},C=function(a){a=B(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",D),f.inspect=function(){return"[Emscripten Module object]"};
else if(ca)"undefined"!=typeof read&&(B=function(a){return read(a)}),C=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(y||z)z?A=self.location.href:"undefined"!==typeof document&&document.currentScript&&(A=document.currentScript.src),A=0!==
A.indexOf("blob:")?A.substr(0,A.lastIndexOf("/")+1):"",B=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},z&&(C=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});f.print||console.log.bind(console);var E=f.printErr||console.warn.bind(console);for(x in r)r.hasOwnProperty(x)&&(f[x]=r[x]);r=null;f.thisProgram&&(aa=f.thisProgram);var F;f.wasmBinary&&(F=f.wasmBinary);var noExitRuntime;
f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&D("no native wasm support detected");var H,fa=!1;function assert(a,b){a||D("Assertion failed: "+b)}var ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ia(a,b){var c=I,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&ha)return ha.decode(c.subarray(a,b));for(d="";a<b;){var g=c[a++];if(g&128){var h=c[a++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|h);else{var n=c[a++]&63;g=224==(g&240)?(g&15)<<12|h<<6|n:(g&7)<<18|h<<12|n<<6|c[a++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}return d}
function ja(a,b,c,d){if(0<d){d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0}}
function ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function ma(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&na[c];)++c;c<<=1;if(32<c-a&&la)return la.decode(I.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var g=J[a+2*d>>1];if(0==g)break;c+=String.fromCharCode(g)}return c}
function oa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var g=0;g<c;++g)J[b>>1]=a.charCodeAt(g),b+=2;J[b>>1]=0;return b-d}function pa(a){return 2*a.length}function qa(a,b){for(var c=0,d="";!(c>=b/4);){var g=K[a+4*c>>2];if(0==g)break;++c;65536<=g?(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023)):d+=String.fromCharCode(g)}return d}
function ra(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}K[b>>2]=h;b+=4;if(b+4>c)break}K[b>>2]=0;return b-d}function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var L,M,I,J,na,K,N,ta,ua,va=f.INITIAL_MEMORY||16777216;f.wasmMemory?H=f.wasmMemory:H=new WebAssembly.Memory({initial:va/65536,maximum:va/65536});
H&&(L=H.buffer);va=L.byteLength;var O=L;L=O;f.HEAP8=M=new Int8Array(O);f.HEAP16=J=new Int16Array(O);f.HEAP32=K=new Int32Array(O);f.HEAPU8=I=new Uint8Array(O);f.HEAPU16=na=new Uint16Array(O);f.HEAPU32=N=new Uint32Array(O);f.HEAPF32=ta=new Float32Array(O);f.HEAPF64=ua=new Float64Array(O);var P,wa=[],xa=[],ya=[],za=[];function Aa(){var a=f.preRun.shift();wa.unshift(a)}var Q=0,Ba=null,R=null;f.preloadedImages={};f.preloadedAudios={};
function D(a){if(f.onAbort)f.onAbort(a);E(a);fa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ca(a){var b=S;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Da(){return Ca("data:application/octet-stream;base64,")}var S="latexParser.wasm";if(!Da()){var Ea=S;S=f.locateFile?f.locateFile(Ea,A):A+Ea}
function Fa(){try{if(F)return new Uint8Array(F);if(C)return C(S);throw"both async and sync fetching of the wasm failed";}catch(a){D(a)}}function Ga(){return F||!y&&!z||"function"!==typeof fetch||Ca("file://")?Promise.resolve().then(Fa):fetch(S,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+S+"'";return a.arrayBuffer()}).catch(function(){return Fa()})}
function Ha(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.O;"number"===typeof c?void 0===b.M?P.get(c)():P.get(c)(b.M):c(void 0===b.M?null:b.M)}}}function Ia(a){this.H=a-16;this.X=function(b){K[this.H+8>>2]=b};this.U=function(b){K[this.H+0>>2]=b};this.V=function(){K[this.H+4>>2]=0};this.T=function(){M[this.H+12>>0]=0};this.W=function(){M[this.H+13>>0]=0};this.R=function(b,c){this.X(b);this.U(c);this.V();this.T();this.W()}}var Ja=0;
function Ka(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var La=void 0;function T(a){for(var b="";I[a];)b+=La[I[a++]];return b}var U={},V={},Ma={};function Na(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Oa(a,b){a=Na(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Pa(a){var b=Error,c=Oa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Qa=void 0;function W(a){throw new Qa(a);}var Ra=void 0;function Sa(a,b){function c(l){l=b(l);if(l.length!==d.length)throw new Ra("Mismatched type converter count");for(var m=0;m<d.length;++m)X(d[m],l[m])}var d=[];d.forEach(function(l){Ma[l]=a});var g=Array(a.length),h=[],n=0;a.forEach(function(l,m){V.hasOwnProperty(l)?g[m]=V[l]:(h.push(l),U.hasOwnProperty(l)||(U[l]=[]),U[l].push(function(){g[m]=V[l];++n;n===h.length&&c(g)}))});0===h.length&&c(g)}
function X(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||W('type "'+d+'" must have a positive integer typeid pointer');if(V.hasOwnProperty(a)){if(c.P)return;W("Cannot register type '"+d+"' twice")}V[a]=b;delete Ma[a];U.hasOwnProperty(a)&&(b=U[a],delete U[a],b.forEach(function(g){g()}))}var Ta=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ua(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ta.length?Ta.pop():Y.length;Y[b]={S:1,value:a};return b}}function Va(a){return this.fromWireType(N[a>>2])}function Wa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Xa(a,b){switch(b){case 2:return function(c){return this.fromWireType(ta[c>>2])};case 3:return function(c){return this.fromWireType(ua[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ya(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Oa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Za(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function ab(a,b){var c=f;if(void 0===c[a].D){var d=c[a];c[a]=function(){c[a].D.hasOwnProperty(arguments.length)||W("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].D+")!");return c[a].D[arguments.length].apply(this,arguments)};c[a].D=[];c[a].D[d.N]=d}}
function bb(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].D&&void 0!==f[a].D[c])&&W("Cannot register public name '"+a+"' twice"),ab(a,a),f.hasOwnProperty(c)&&W("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].D[c]=b):(f[a]=b,void 0!==c&&(f[a].da=c))}function cb(a,b){for(var c=[],d=0;d<a;d++)c.push(K[(b>>2)+d]);return c}
function db(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var g;-1!=a.indexOf("j")?g=c&&c.length?f["dynCall_"+a].apply(null,[b].concat(c)):f["dynCall_"+a].call(null,b):g=P.get(b).apply(null,c);return g}}function eb(a,b){a=T(a);var c=-1!=a.indexOf("j")?db(a,b):P.get(b);"function"!==typeof c&&W("unknown function pointer with signature "+a+": "+b);return c}
var fb=void 0;function gb(a){a=hb(a);var b=T(a);Z(a);return b}function ib(a,b){function c(h){g[h]||V[h]||(Ma[h]?Ma[h].forEach(c):(d.push(h),g[h]=!0))}var d=[],g={};b.forEach(c);throw new fb(a+": "+d.map(gb).join([", "]));}
function jb(a,b,c){switch(b){case 0:return c?function(d){return M[d]}:function(d){return I[d]};case 1:return c?function(d){return J[d>>1]}:function(d){return na[d>>1]};case 2:return c?function(d){return K[d>>2]}:function(d){return N[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var kb={};
function lb(){if(!mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in kb)a[b]=kb[b];var c=[];for(b in a)c.push(b+"="+a[b]);mb=c}return mb}var mb;function nb(a){return 0===a%4&&(0!==a%100||0===a%400)}function ob(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var pb=[31,29,31,30,31,30,31,31,30,31,30,31],qb=[31,28,31,30,31,30,31,31,30,31,30,31];function rb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(nb(a.getFullYear())?pb:qb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function sb(a,b,c,d){function g(e,k,t){for(e="number"===typeof e?e.toString():e||"";e.length<k;)e=t[0]+e;return e}function h(e,k){return g(e,k,"0")}function n(e,k){function t(G){return 0>G?-1:0<G?1:0}var v;0===(v=t(e.getFullYear()-k.getFullYear()))&&0===(v=t(e.getMonth()-k.getMonth()))&&(v=t(e.getDate()-k.getDate()));return v}function l(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function m(e){e=rb(new Date(e.C+1900,0,1),e.L);var k=new Date(e.getFullYear()+1,0,4),t=l(new Date(e.getFullYear(),0,4));k=l(k);return 0>=n(t,e)?0>=n(k,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var p=K[d+40>>2];d={$:K[d>>2],Z:K[d+4>>2],J:K[d+8>>2],I:K[d+12>>2],G:K[d+16>>2],C:K[d+20>>2],K:K[d+24>>2],L:K[d+28>>2],ea:K[d+32>>2],Y:K[d+36>>2],aa:p?
p?ia(p,void 0):"":""};c=c?ia(c,void 0):"";p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in p)c=c.replace(new RegExp(q,"g"),p[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");p={"%a":function(e){return u[e.K].substring(0,3)},"%A":function(e){return u[e.K]},"%b":function(e){return w[e.G].substring(0,3)},"%B":function(e){return w[e.G]},"%C":function(e){return h((e.C+1900)/100|0,2)},"%d":function(e){return h(e.I,2)},"%e":function(e){return g(e.I,2," ")},"%g":function(e){return m(e).toString().substring(2)},"%G":function(e){return m(e)},"%H":function(e){return h(e.J,2)},"%I":function(e){e=
e.J;0==e?e=12:12<e&&(e-=12);return h(e,2)},"%j":function(e){return h(e.I+ob(nb(e.C+1900)?pb:qb,e.G-1),3)},"%m":function(e){return h(e.G+1,2)},"%M":function(e){return h(e.Z,2)},"%n":function(){return"\n"},"%p":function(e){return 0<=e.J&&12>e.J?"AM":"PM"},"%S":function(e){return h(e.$,2)},"%t":function(){return"\t"},"%u":function(e){return e.K||7},"%U":function(e){var k=new Date(e.C+1900,0,1),t=0===k.getDay()?k:rb(k,7-k.getDay());e=new Date(e.C+1900,e.G,e.I);return 0>n(t,e)?h(Math.ceil((31-t.getDate()+
(ob(nb(e.getFullYear())?pb:qb,e.getMonth()-1)-31)+e.getDate())/7),2):0===n(t,k)?"01":"00"},"%V":function(e){var k=new Date(e.C+1901,0,4),t=l(new Date(e.C+1900,0,4));k=l(k);var v=rb(new Date(e.C+1900,0,1),e.L);return 0>n(v,t)?"53":0>=n(k,v)?"01":h(Math.ceil((t.getFullYear()<e.C+1900?e.L+32-t.getDate():e.L+1-t.getDate())/7),2)},"%w":function(e){return e.K},"%W":function(e){var k=new Date(e.C,0,1),t=1===k.getDay()?k:rb(k,0===k.getDay()?1:7-k.getDay()+1);e=new Date(e.C+1900,e.G,e.I);return 0>n(t,e)?h(Math.ceil((31-
t.getDate()+(ob(nb(e.getFullYear())?pb:qb,e.getMonth()-1)-31)+e.getDate())/7),2):0===n(t,k)?"01":"00"},"%y":function(e){return(e.C+1900).toString().substring(2)},"%Y":function(e){return e.C+1900},"%z":function(e){e=e.Y;var k=0<=e;e=Math.abs(e)/60;return(k?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.aa},"%%":function(){return"%"}};for(q in p)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),p[q](d)));q=tb(c);if(q.length>b)return 0;M.set(q,a);return q.length-1}
for(var ub=Array(256),vb=0;256>vb;++vb)ub[vb]=String.fromCharCode(vb);La=ub;Qa=f.BindingError=Pa("BindingError");Ra=f.InternalError=Pa("InternalError");f.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};fb=f.UnboundTypeError=Pa("UnboundTypeError");function tb(a){var b=Array(ka(a)+1);ja(a,b,0,b.length);return b}xa.push({O:function(){wb()}});
var yb={b:function(a){return xb(a+16)+16},c:function(a,b,c){(new Ia(a)).R(b,c);Ja++;throw a;},k:function(a,b,c,d,g){var h=Ka(c);b=T(b);X(a,{name:b,fromWireType:function(n){return!!n},toWireType:function(n,l){return l?d:g},argPackAdvance:8,readValueFromPointer:function(n){if(1===c)var l=M;else if(2===c)l=J;else if(4===c)l=K;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[n>>h])},F:null})},j:function(a,b){b=T(b);X(a,{name:b,fromWireType:function(c){var d=Y[c].value;
4<c&&0===--Y[c].S&&(Y[c]=void 0,Ta.push(c));return d},toWireType:function(c,d){return Ua(d)},argPackAdvance:8,readValueFromPointer:Va,F:null})},g:function(a,b,c){c=Ka(c);b=T(b);X(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,g){if("number"!==typeof g&&"boolean"!==typeof g)throw new TypeError('Cannot convert "'+Wa(g)+'" to '+this.name);return g},argPackAdvance:8,readValueFromPointer:Xa(b,c),F:null})},r:function(a,b,c,d,g,h){var n=cb(b,c);a=T(a);g=eb(d,g);bb(a,function(){ib("Cannot call "+
a+" due to unbound types",n)},b-1);Sa(n,function(l){var m=[l[0],null].concat(l.slice(1)),p=l=a,q=g,u=m.length;2>u&&W("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var w=null!==m[1]&&!1,e=!1,k=1;k<m.length;++k)if(null!==m[k]&&void 0===m[k].F){e=!0;break}var t="void"!==m[0].name,v="",G="";for(k=0;k<u-2;++k)v+=(0!==k?", ":"")+"arg"+k,G+=(0!==k?", ":"")+"arg"+k+"Wired";p="return function "+Na(p)+"("+v+") {\nif (arguments.length !== "+(u-2)+") {\nthrowBindingError('function "+
p+" called with ' + arguments.length + ' arguments, expected "+(u-2)+" args!');\n}\n";e&&(p+="var destructors = [];\n");var $a=e?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[W,q,h,Za,m[0],m[1]];w&&(p+="var thisWired = classParam.toWireType("+$a+", this);\n");for(k=0;k<u-2;++k)p+="var arg"+k+"Wired = argType"+k+".toWireType("+$a+", arg"+k+"); // "+m[k+2].name+"\n",v.push("argType"+k),q.push(m[k+2]);w&&(G="thisWired"+(0<G.length?", ":"")+G);p+=
(t?"var rv = ":"")+"invoker(fn"+(0<G.length?", ":"")+G+");\n";if(e)p+="runDestructors(destructors);\n";else for(k=w?1:2;k<m.length;++k)u=1===k?"thisWired":"arg"+(k-2)+"Wired",null!==m[k].F&&(p+=u+"_dtor("+u+"); // "+m[k].name+"\n",v.push(u+"_dtor"),q.push(m[k].F));t&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");v.push(p+"}\n");m=Ya(v).apply(null,q);k=b-1;if(!f.hasOwnProperty(l))throw new Ra("Replacing nonexistant public symbol");void 0!==f[l].D&&void 0!==k?f[l].D[k]=m:(f[l]=m,f[l].N=
k);return[]})},e:function(a,b,c,d,g){function h(p){return p}b=T(b);-1===g&&(g=4294967295);var n=Ka(c);if(0===d){var l=32-8*c;h=function(p){return p<<l>>>l}}var m=-1!=b.indexOf("unsigned");X(a,{name:b,fromWireType:h,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Wa(q)+'" to '+this.name);if(q<d||q>g)throw new TypeError('Passing a number "'+Wa(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+
d+", "+g+"]!");return m?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:jb(b,n,0!==d),F:null})},d:function(a,b,c){function d(h){h>>=2;return new g(L,N[h+1],N[h])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);X(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{P:!0})},h:function(a,b){b=T(b);var c="std::string"===b;X(a,{name:b,fromWireType:function(d){var g=N[d>>2];if(c)for(var h=d+4,n=0;n<=g;++n){var l=d+4+n;if(n==g||
0==I[l]){h=h?ia(h,l-h):"";if(void 0===m)var m=h;else m+=String.fromCharCode(0),m+=h;h=l+1}}else{m=Array(g);for(n=0;n<g;++n)m[n]=String.fromCharCode(I[d+4+n]);m=m.join("")}Z(d);return m},toWireType:function(d,g){g instanceof ArrayBuffer&&(g=new Uint8Array(g));var h="string"===typeof g;h||g instanceof Uint8Array||g instanceof Uint8ClampedArray||g instanceof Int8Array||W("Cannot pass non-string to std::string");var n=(c&&h?function(){return ka(g)}:function(){return g.length})(),l=xb(4+n+1);N[l>>2]=n;
if(c&&h)ja(g,I,l+4,n+1);else if(h)for(h=0;h<n;++h){var m=g.charCodeAt(h);255<m&&(Z(l),W("String has UTF-16 code units that do not fit in 8 bits"));I[l+4+h]=m}else for(h=0;h<n;++h)I[l+4+h]=g[h];null!==d&&d.push(Z,l);return l},argPackAdvance:8,readValueFromPointer:Va,F:function(d){Z(d)}})},f:function(a,b,c){c=T(c);if(2===b){var d=ma;var g=oa;var h=pa;var n=function(){return na};var l=1}else 4===b&&(d=qa,g=ra,h=sa,n=function(){return N},l=2);X(a,{name:c,fromWireType:function(m){for(var p=N[m>>2],q=n(),
u,w=m+4,e=0;e<=p;++e){var k=m+4+e*b;if(e==p||0==q[k>>l])w=d(w,k-w),void 0===u?u=w:(u+=String.fromCharCode(0),u+=w),w=k+b}Z(m);return u},toWireType:function(m,p){"string"!==typeof p&&W("Cannot pass non-string to C++ string type "+c);var q=h(p),u=xb(4+q+b);N[u>>2]=q>>l;g(p,u+4,q+b);null!==m&&m.push(Z,u);return u},argPackAdvance:8,readValueFromPointer:Va,F:function(m){Z(m)}})},l:function(a,b){b=T(b);X(a,{ba:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},i:function(){D()},
m:function(a,b,c){I.copyWithin(a,b,b+c)},n:function(){D("OOM")},p:function(a,b){var c=0;lb().forEach(function(d,g){var h=b+c;g=K[a+4*g>>2]=h;for(h=0;h<d.length;++h)M[g++>>0]=d.charCodeAt(h);M[g>>0]=0;c+=d.length+1});return 0},q:function(a,b){var c=lb();K[a>>2]=c.length;var d=0;c.forEach(function(g){d+=g.length+1});K[b>>2]=d;return 0},a:H,o:function(a,b,c,d){return sb(a,b,c,d)}};
(function(){function a(g){f.asm=g.exports;P=f.asm.s;Q--;f.monitorRunDependencies&&f.monitorRunDependencies(Q);0==Q&&(null!==Ba&&(clearInterval(Ba),Ba=null),R&&(g=R,R=null,g()))}function b(g){a(g.instance)}function c(g){return Ga().then(function(h){return WebAssembly.instantiate(h,d)}).then(g,function(h){E("failed to asynchronously prepare wasm: "+h);D(h)})}var d={a:yb};Q++;f.monitorRunDependencies&&f.monitorRunDependencies(Q);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(g){return E("Module.instantiateWasm callback failed with error: "+
g),!1}(function(){return F||"function"!==typeof WebAssembly.instantiateStreaming||Da()||Ca("file://")||"function"!==typeof fetch?c(b):fetch(S,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(b,function(h){E("wasm streaming compile failed: "+h);E("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var wb=f.___wasm_call_ctors=function(){return(wb=f.___wasm_call_ctors=f.asm.t).apply(null,arguments)},xb=f._malloc=function(){return(xb=f._malloc=f.asm.u).apply(null,arguments)},hb=f.___getTypeName=function(){return(hb=f.___getTypeName=f.asm.v).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.w).apply(null,arguments)};var Z=f._free=function(){return(Z=f._free=f.asm.x).apply(null,arguments)};
f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.y).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.z).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.A).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.B).apply(null,arguments)};var zb;R=function Ab(){zb||Bb();zb||(R=Ab)};
function Bb(){function a(){if(!zb&&(zb=!0,f.calledRun=!0,!fa)){Ha(xa);Ha(ya);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();za.unshift(b)}Ha(za)}}if(!(0<Q)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Aa();Ha(wa);0<Q||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}
f.run=Bb;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();noExitRuntime=!0;Bb();
